version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: KCMKI

    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"